name: solarized_flutter
description: A new Flutter package project.
version: 0.0.1
author: M J Stanway
homepage: otter.works

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
